theme: jekyll-theme-cayman
# Site settings
title: 0x6768编程技术
SEOTitle: 0x6768编程技术
header-img: img/post-bg-desk.jpg
email: 272591929@qq.com
description: "Every failure is leading towards success."
keyword: "0x6768编程技术, yaron"
url: "http://0x6768.com/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yangyong1011/yangyong1011.github.io.git" # you code repository

